name: Basic Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: Person to greet
        default: "World"
        required: true
        type: string
      city:
        description: Favorite city
        required: true
        default: "San Francisco"
        type: choice
        options:
          - San Francisco
          - New York
          - Los Angeles
          - Chicago
      favorite_number:
        description: Favorite number
        required: true
        default: "7"
        type: number

jobs:
  greet:
    name: "Greetings User"
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "Hello ${{ github.event.inputs.name }} from ${{ github.event.inputs.city }}"
          echo "Is your favorite number ${{ github.event.inputs.favorite_number }}?"